substitutions:
  _REGION: australia-southeast1
  _WEB_SVC: parenthub-web
  _API_SVC: parenthub-api
  _TAG: v1-$BUILD_ID
  _AZURE_CLIENT_ID: "52ea052d-6dc9-4ead-bd6c-866acd522227"
  _AZURE_TENANT_ID: "6710fdee-7f27-4a98-9c77-b290f13a24c1"
  _AZURE_CLIENT_SECRET_SECRET: "PARENTHUB_AZURE_CLIENT_SECRET"

steps:
# 1) Build & push API
- name: gcr.io/cloud-builders/docker
  args: ['build','-f','server/Dockerfile','-t','gcr.io/$PROJECT_ID/$(_API_SVC):$(_TAG)','server']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/$(_API_SVC):$(_TAG)']

# 2) Deploy API (so we know its real URL)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    ['run','deploy','$(_API_SVC)',
     '--image=gcr.io/$PROJECT_ID/$(_API_SVC):$(_TAG)',
     '--platform=managed','--region=$(_REGION)','--allow-unauthenticated',
     '--port=5180','--cpu=1','--memory=512Mi','--concurrency=80','--min-instances=0','--max-instances=3'
     # add env/secrets here if you use them, e.g.:
     # '--set-secrets=DATABASE_URL=projects/$PROJECT_ID/secrets/PARENTHUB_DB_URL:latest'
    ]

# 3) Read API URL for the frontend build
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      API_URL=$(gcloud run services describe "$_API_SVC" --region="$_REGION" --format='value(status.url)')
      echo -n "$API_URL" > api_url.txt
      echo "API_URL=$API_URL"

# 3b) Update API service with Entra ID env + secret
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      API_URL=$(cat api_url.txt)
      gcloud run services update "$_API_SVC" \
        --region="$_REGION" --platform=managed \
        --set-env-vars=AZURE_CLIENT_ID=${_AZURE_CLIENT_ID},AZURE_TENANT_ID=${_AZURE_TENANT_ID},AZURE_REDIRECT_URI="${API_URL}/api/auth/azure/callback" \
        --set-secrets=AZURE_CLIENT_SECRET=${_AZURE_CLIENT_SECRET_SECRET}:latest

# 4) Build & push Web with the real API URL baked in
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - -c
    - |
      API_URL=$(cat api_url.txt)
      docker build -f Dockerfile.web \
        --build-arg VITE_API_BASE_URL="$API_URL" \
        --build-arg VITE_MSAL_CLIENT_ID="$_AZURE_CLIENT_ID" \
        --build-arg VITE_MSAL_TENANT_ID="$_AZURE_TENANT_ID" \
        -t gcr.io/$PROJECT_ID/$(_WEB_SVC):$(_TAG) .
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/$(_WEB_SVC):$(_TAG)']

# 5) Deploy Web
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    ['run','deploy','$(_WEB_SVC)',
     '--image=gcr.io/$PROJECT_ID/$(_WEB_SVC):$(_TAG)',
     '--platform=managed','--region=$(_REGION)','--allow-unauthenticated',
     '--port=8080','--cpu=1','--memory=256Mi','--concurrency=150','--min-instances=0','--max-instances=3']

images:
- gcr.io/$PROJECT_ID/$(_API_SVC):$(_TAG)
- gcr.io/$PROJECT_ID/$(_WEB_SVC):$(_TAG)