substitutions:
  _REGION: australia-southeast1
  _SERVICE: parenthub-api-prod
  _IMAGE: gcr.io/$PROJECT_ID/parenthub-api:$COMMIT_SHA

timeout: "1800s"

availableSecrets:
  secretManager:
    # DB – used during build/migrate step
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/DIRECT_URL/versions/latest
      env: DIRECT_URL

steps:
  # 1) Install, generate Prisma, run migrations, build server
  - name: node:20
    id: "build-and-migrate"
    entrypoint: bash
    secretEnv:
      - DATABASE_URL
      - DIRECT_URL
    args:
      - -lc
      - |
        set -euo pipefail
        npm ci
        npx prisma generate --schema server/prisma/schema.prisma
        # Use DIRECT_URL for migrations if present
        if [ -n "${DIRECT_URL:-}" ]; then
          export DATABASE_URL="$$DIRECT_URL"
        fi
        npx prisma migrate deploy --schema server/prisma/schema.prisma
        npm run build

  # 2) Build & push the API image
  - name: gcr.io/cloud-builders/docker
    id: "docker-build"
    args: ["build", "-f", "server/Dockerfile", "-t", "$_IMAGE", "."]
  - name: gcr.io/cloud-builders/docker
    id: "docker-push"
    args: ["push", "$_IMAGE"]

  # 3) Deploy to Cloud Run and MAP secrets to the env names your code expects
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "deploy-cloud-run"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_IMAGE
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated

      # Secrets → ENV (left side = ENV var name the app reads)
      - --set-secrets=CLIENT_APP_ORIGIN=projects/$PROJECT_ID/secrets/FRONTEND_ORIGIN:latest
      - --set-secrets=AUTH_ALLOWED_ORIGIN=projects/$PROJECT_ID/secrets/AUTH_ALLOWED_ORIGIN:latest

      # Your code requires AZURE_* names; secrets are named ENTRA_* — map them here:
      - --set-secrets=AZURE_TENANT_ID=projects/$PROJECT_ID/secrets/ENTRA_TENANT_ID:latest
      - --set-secrets=AZURE_CLIENT_ID=projects/$PROJECT_ID/secrets/ENTRA_CLIENT_ID:latest
      - --set-secrets=AZURE_CLIENT_SECRET=projects/$PROJECT_ID/secrets/ENTRA_CLIENT_SECRET:latest

      # Secret currently called AUTH_REDIRECT_URI; app expects AZURE_REDIRECT_URI
      - --set-secrets=AZURE_REDIRECT_URI=projects/$PROJECT_ID/secrets/AUTH_REDIRECT_URI:latest

      # Other app secrets
      - --set-secrets=SESSION_SECRET=projects/$PROJECT_ID/secrets/SESSION_SECRET:latest
      - --set-secrets=DATABASE_URL=projects/$PROJECT_ID/secrets/DATABASE_URL:latest
      - --set-secrets=DIRECT_URL=projects/$PROJECT_ID/secrets/DIRECT_URL:latest

images:
  - $_IMAGE
